// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/kv.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderRedirect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderRedirect) Reset() {
	*x = LeaderRedirect{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderRedirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderRedirect) ProtoMessage() {}

func (x *LeaderRedirect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderRedirect.ProtoReflect.Descriptor instead.
func (*LeaderRedirect) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderRedirect) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *LeaderRedirect) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Skip the read barrier. Faster, but the value may be out of date if this
	// node has been cut off from the cluster without noticing.
	AllowStale    bool `protobuf:"varint,2,opt,name=allow_stale,json=allowStale,proto3" json:"allow_stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetAllowStale() bool {
	if x != nil {
		return x.AllowStale
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PutRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *PutResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeleteRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

type CompareAndSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expected      string                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareAndSwapRequest) Reset() {
	*x = CompareAndSwapRequest{}
	mi := &file_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSwapRequest) ProtoMessage() {}

func (x *CompareAndSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSwapRequest.ProtoReflect.Descriptor instead.
func (*CompareAndSwapRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *CompareAndSwapRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CompareAndSwapRequest) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *CompareAndSwapRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CompareAndSwapRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CompareAndSwapRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type CompareAndSwapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Swapped       bool                   `protobuf:"varint,2,opt,name=swapped,proto3" json:"swapped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareAndSwapResponse) Reset() {
	*x = CompareAndSwapResponse{}
	mi := &file_proto_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSwapResponse) ProtoMessage() {}

func (x *CompareAndSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSwapResponse.ProtoReflect.Descriptor instead.
func (*CompareAndSwapResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{8}
}

func (x *CompareAndSwapResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

func (x *CompareAndSwapResponse) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

type AddServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerRequest) Reset() {
	*x = AddServerRequest{}
	mi := &file_proto_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerRequest) ProtoMessage() {}

func (x *AddServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerRequest.ProtoReflect.Descriptor instead.
func (*AddServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{9}
}

func (x *AddServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerResponse) Reset() {
	*x = AddServerResponse{}
	mi := &file_proto_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerResponse) ProtoMessage() {}

func (x *AddServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerResponse.ProtoReflect.Descriptor instead.
func (*AddServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{10}
}

func (x *AddServerResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

type RemoveServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerRequest) Reset() {
	*x = RemoveServerRequest{}
	mi := &file_proto_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerRequest) ProtoMessage() {}

func (x *RemoveServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerResponse) Reset() {
	*x = RemoveServerResponse{}
	mi := &file_proto_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerResponse) ProtoMessage() {}

func (x *RemoveServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerResponse.ProtoReflect.Descriptor instead.
func (*RemoveServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveServerResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

type MembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersRequest) Reset() {
	*x = MembersRequest{}
	mi := &file_proto_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersRequest) ProtoMessage() {}

func (x *MembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersRequest.ProtoReflect.Descriptor instead.
func (*MembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{13}
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Voter         bool                   `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{14}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

type MembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redirect      *LeaderRedirect        `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Members       []*Member              `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersResponse) Reset() {
	*x = MembersResponse{}
	mi := &file_proto_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersResponse) ProtoMessage() {}

func (x *MembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersResponse.ProtoReflect.Descriptor instead.
func (*MembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{15}
}

func (x *MembersResponse) GetRedirect() *LeaderRedirect {
	if x != nil {
		return x.Redirect
	}
	return nil
}

func (x *MembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MembersResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x04raft\"T\n" +
	"\x0eLeaderRedirect\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\"?\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\vallow_stale\x18\x02 \x01(\bR\n" +
	"allowStale\"k\n" +
	"\vGetResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"c\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\"?\n" +
	"\vPutResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\"P\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"B\n" +
	"\x0eDeleteResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\"\x8a\x01\n" +
	"\x15CompareAndSwapRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\tR\bexpected\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\"d\n" +
	"\x16CompareAndSwapResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\x12\x18\n" +
	"\aswapped\x18\x02 \x01(\bR\aswapped\"<\n" +
	"\x10AddServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"E\n" +
	"\x11AddServerResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\"%\n" +
	"\x13RemoveServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x14RemoveServerResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\"\x10\n" +
	"\x0eMembersRequest\"H\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05voter\x18\x03 \x01(\bR\x05voter\"\x88\x01\n" +
	"\x0fMembersResponse\x120\n" +
	"\bredirect\x18\x01 \x01(\v2\x14.raft.LeaderRedirectR\bredirect\x12&\n" +
	"\amembers\x18\x02 \x03(\v2\f.raft.MemberR\amembers\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId2\xa2\x03\n" +
	"\tKVService\x12*\n" +
	"\x03Get\x12\x10.raft.GetRequest\x1a\x11.raft.GetResponse\x12*\n" +
	"\x03Put\x12\x10.raft.PutRequest\x1a\x11.raft.PutResponse\x123\n" +
	"\x06Delete\x12\x13.raft.DeleteRequest\x1a\x14.raft.DeleteResponse\x12K\n" +
	"\x0eCompareAndSwap\x12\x1b.raft.CompareAndSwapRequest\x1a\x1c.raft.CompareAndSwapResponse\x12<\n" +
	"\tAddServer\x12\x16.raft.AddServerRequest\x1a\x17.raft.AddServerResponse\x12E\n" +
	"\fRemoveServer\x12\x19.raft.RemoveServerRequest\x1a\x1a.raft.RemoveServerResponse\x126\n" +
	"\aMembers\x12\x14.raft.MembersRequest\x1a\x15.raft.MembersResponseB-Z+github.com/krithik-sri/raft-kv/proto;raftpbb\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_kv_proto_goTypes = []any{
	(*LeaderRedirect)(nil),         // 0: raft.LeaderRedirect
	(*GetRequest)(nil),             // 1: raft.GetRequest
	(*GetResponse)(nil),            // 2: raft.GetResponse
	(*PutRequest)(nil),             // 3: raft.PutRequest
	(*PutResponse)(nil),            // 4: raft.PutResponse
	(*DeleteRequest)(nil),          // 5: raft.DeleteRequest
	(*DeleteResponse)(nil),         // 6: raft.DeleteResponse
	(*CompareAndSwapRequest)(nil),  // 7: raft.CompareAndSwapRequest
	(*CompareAndSwapResponse)(nil), // 8: raft.CompareAndSwapResponse
	(*AddServerRequest)(nil),       // 9: raft.AddServerRequest
	(*AddServerResponse)(nil),      // 10: raft.AddServerResponse
	(*RemoveServerRequest)(nil),    // 11: raft.RemoveServerRequest
	(*RemoveServerResponse)(nil),   // 12: raft.RemoveServerResponse
	(*MembersRequest)(nil),         // 13: raft.MembersRequest
	(*Member)(nil),                 // 14: raft.Member
	(*MembersResponse)(nil),        // 15: raft.MembersResponse
}
var file_proto_kv_proto_depIdxs = []int32{
	0,  // 0: raft.GetResponse.redirect:type_name -> raft.LeaderRedirect
	0,  // 1: raft.PutResponse.redirect:type_name -> raft.LeaderRedirect
	0,  // 2: raft.DeleteResponse.redirect:type_name -> raft.LeaderRedirect
	0,  // 3: raft.CompareAndSwapResponse.redirect:type_name -> raft.LeaderRedirect
	0,  // 4: raft.AddServerResponse.redirect:type_name -> raft.LeaderRedirect
	0,  // 5: raft.RemoveServerResponse.redirect:type_name -> raft.LeaderRedirect
	0,  // 6: raft.MembersResponse.redirect:type_name -> raft.LeaderRedirect
	14, // 7: raft.MembersResponse.members:type_name -> raft.Member
	1,  // 8: raft.KVService.Get:input_type -> raft.GetRequest
	3,  // 9: raft.KVService.Put:input_type -> raft.PutRequest
	5,  // 10: raft.KVService.Delete:input_type -> raft.DeleteRequest
	7,  // 11: raft.KVService.CompareAndSwap:input_type -> raft.CompareAndSwapRequest
	9,  // 12: raft.KVService.AddServer:input_type -> raft.AddServerRequest
	11, // 13: raft.KVService.RemoveServer:input_type -> raft.RemoveServerRequest
	13, // 14: raft.KVService.Members:input_type -> raft.MembersRequest
	2,  // 15: raft.KVService.Get:output_type -> raft.GetResponse
	4,  // 16: raft.KVService.Put:output_type -> raft.PutResponse
	6,  // 17: raft.KVService.Delete:output_type -> raft.DeleteResponse
	8,  // 18: raft.KVService.CompareAndSwap:output_type -> raft.CompareAndSwapResponse
	10, // 19: raft.KVService.AddServer:output_type -> raft.AddServerResponse
	12, // 20: raft.KVService.RemoveServer:output_type -> raft.RemoveServerResponse
	15, // 21: raft.KVService.Members:output_type -> raft.MembersResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
