syntax = "proto3";

package raft;

option go_package = "github.com/krithik-sri/raft-kv/proto;raftpb";

service KVService {
    rpc Get(GetRequest) returns (GetResponse);
    rpc Put(PutRequest) returns (PutResponse);
    rpc Delete(DeleteRequest) returns (DeleteResponse);
    rpc CompareAndSwap(CompareAndSwapRequest) returns (CompareAndSwapResponse);
}

message LeaderRedirect {
    string leader_id = 1;
    string leader_address = 2;
}

message GetRequest {
    string key = 1;
}

message GetResponse {
    LeaderRedirect redirect = 1;
    string value = 2;
    bool found = 3;
}

message PutRequest {
    string key = 1;
    string value = 2;
    string client_id = 3;
    uint64 seq = 4;
}

message PutResponse {
    LeaderRedirect redirect = 1;
}

message DeleteRequest {
    string key = 1;
    string client_id = 2;
    uint64 seq = 3;
}

message DeleteResponse {
    LeaderRedirect redirect = 1;
}

message CompareAndSwapRequest {
    string key = 1;
    string expected = 2;
    string value = 3;
    string client_id = 4;
    uint64 seq = 5;
}

message CompareAndSwapResponse {
    LeaderRedirect redirect = 1;
    bool swapped = 2;
}
